### ISSUE TITLE
Not showing event over multiple days

### ISSUE THREAD

**Issue by stianjaco** [u01jmg3/ics-parser#73] opened 2016-09-05 08:30 UTC
If I have an event that starts Monday and ends Sunday, the event will not show if using `eventsFromRange()` even if the day is right.

**Comment by u01jmg3** [comment] 2016-09-05 11:10
Feel free to PR; this library is not currently in active development. Bugs will be fixed but enhancements will be added to a prioritised queue.

**Comment by u01jmg3** [comment] 2016-09-07 17:30
If you provide an iCal snippet that will allows us to replicate the problem on our end.

**Comment by u01jmg3** [comment] 2016-10-09 01:12
- No iCal snippet provided so unable to reproduce the problem
- Happy to re-open if one is provided

**Closed by u01jmg3** 2016-10-09 01:12 UTC
Labels: awaiting-feedback, bug, to-be-investigated
