### ISSUE TITLE
Support 'RRULE:FREQ=MONTHLY;BYDAY=1SU,3SU;UNTIL=xxxxx

### ISSUE THREAD

**Issue by scottatmonk** [u01jmg3/ics-parser#235] opened 2019-08-06 19:07 UTC
PHP Version: 7.3.1
    ICS Parser Version: 2.1.13
    Mac

Description of the Issue:

RRULE:FREQ=MONTHLY;BYDAY=1SU,3SU;UNTIL=xxxxx is leaving off second day ie. ,3SU

**Comment by s0600204** [comment] 2019-08-06 21:49
(Duplicate of #15, is it not?)

**Comment by u01jmg3** [comment] 2019-08-06 21:52
Closing in favour of #156 

@scottatmonk: happy to accept a PR should you wish to have this functionality

**Closed by u01jmg3** 2019-08-06 21:52 UTC
Labels: to-be-investigated
