### ISSUE TITLE
Add timezone support

### ISSUE THREAD

**Issue by Nilpferdschaf** [u01jmg3/ics-parser#53] opened 2016-04-26 13:12 UTC
I'm currently working with a server that produces output like this:

```
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:5 appointments
DTSTART;TZID=Europe/Berlin:20160425T150000
DTEND;TZID=Europe/Berlin:20160425T160000
RRULE:FREQ=DAILY;UNTIL=20160429T130000Z
END:VEVENT
```

Notice how the timezone is included in the `DTSTART` and `DTEND` properties, but not in the `RRULE` > `UNTIL` property. This means that the `RRULE` parsing doesn't work properly and the last event is always left out. It is of course an awfully convoluted output, but it technically lies within specifications.

I could take the time to implement this, but I want to make sure the way I do it is compatible with the current code/design philosophy. Does anyone have ideas how this could be accomplished without changing too much of the existing code? I propose a new class RRule that takes a `DTSTART`, `RRULE`s and `EXDATE`s and turns them into a stream of timestamps. This could be used to streamline the `process_recurrences()` method as well as figuring out which time offset to use (the offset in my example changes depending on whether daylight savings time is in effect, which is specified by two `RRULE`s). 

After that is done, you could easily modify `iCalDateToUnixTimestamp()` to account for the timezone.

**Comment by u01jmg3** [comment] 2016-04-26 14:24
For your issue, I don't believe a new class is required. If one event is missing from your occurrence rule when `UNTIL` is used in combination with a timezone then perhaps that is what you should look to fix.

**Comment by u01jmg3** [comment] 2016-10-09 01:17
Your issue may have been fixed with 15ad353

**Comment by grimmlink** [comment] 2016-11-17 17:56
Hi,

I have a related situation with timezones.
One of my calendar contains recurrent events that have been created with Europe/Paris TZ during DST (summer time). The weekly event looks like this:

```
BEGIN:VEVENT
DTSTART;TZID=Europe/Paris:20160921T080000
DTEND;TZID=Europe/Paris:20160921T090000
RRULE:FREQ=WEEKLY;BYDAY=WE
DTSTAMP:20161117T165045Z
UID:------------------------@google.com
CREATED:20160920T133918Z
DESCRIPTION:
LAST-MODIFIED:20160920T133923Z
LOCATION:
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:---------
TRANSP:OPAQUE
END:VEVENT
```

Start time is 8am in Paris TZ (2 hours offset with UTC is 6am).
Problem is now that the DST is finished we are back to a 1 hour offset but this is what i get from the parser: `20161116T060000Z` instead of `20161116T070000Z`

Any idea ?
I'll try to work on a PR as I may have a lead with http://php.net/manual/datetimezone.gettransitions.php

**Comment by u01jmg3** [comment] 2016-11-17 18:43
Off the top of my head I do not know nor have I seen this before. Happy to accept a PR if you figure out the problem.

**Comment by grimmlink** [comment] 2016-11-18 13:20
The problem is that the DTSTART is converted to timestamp before to manage the recurrences
so `DTSTART;TZID=Europe/Paris:20160923T153000` becomes `2016-09-23 13:30:00` in unix time

Then there is no way to know in the processRecurrences function if the first occurence of the event was created during DST or not

I looked at the code, but there are too many things to change, would be easier to acutally rewrite everythng using DateTimes

**Comment by grimmlink** [comment] 2016-11-18 13:46
#94

**Closed** 2016-11-19 15:26 UTC
Labels: enhancement, external-request, to-be-investigated
